### ISSUE TITLE
1.0.0: pytest is failing

### ISSUE THREAD

**Issue by kloczek** [mdmintz/sbVirtualDisplay#1]
I'm trying to package your module as an rpm package. So I'm using the typical build, install and test cycle used on building packages from non-root account.
- "setup.py build"
- "setup.py install --root </install/prefix>"
- "pytest with PYTHONPATH pointing to sitearch and sitelib inside </install/prefix>

Here is pytest output:
```console
+ PYTHONPATH=/data/home/tkloczko/rpmbuild/BUILDROOT/python-sbvirtualdisplay-1.0.0-2.fc35.x86_64/usr/lib64/python3.8/site-packages:/data/home/tkloczko/rpmbuild/BUILDROOT/python-sbvirtualdisplay-1.0.0-2.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/_pytest/main.py", line 265, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 982, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/hooks.py", line 308, in call_historic
INTERNALERROR>     res = self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pytest_randomly.py", line 109, in pytest_configure
INTERNALERROR>     config.cache.set("randomly_seed", seed)
INTERNALERROR> AttributeError: 'Config' object has no attribute 'cache'
```

**Comment by mdmintz** [comment]
@kloczek This is what I see when running ``pytest``:

```bash
=================================== test session starts ====================================
platform darwin -- Python 3.9.2, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /Users/michael/github/sbVirtualDisplay, configfile: pytest.ini
plugins: html-2.0.1, xdist-2.5.0, forked-1.4.0, rerunfailures-10.2, metadata-1.11.0, ordering-0.6, cov-3.0.0, seleniumbase-2.2.9
collected 1 item                                                                           

tests/test_basic_flow.py <Display cmd_param=['Xvfb', '-br', '-nolisten', 'tcp', '-screen', '0', '1440x1880x24', ':1001'] cmd=['Xvfb', '-br', '-nolisten', 'tcp', '-screen', '0', '1440x1880x24', ':1001'] oserror=None return_code=None stdout="None" stderr="None" timeout_happened=False>
.

==================================== 1 passed in 0.21s =====================================
```

Installation is done via ``pip install``, so I'm not sure why you'd need the RPM. And it appears your stack trace doesn't point to any lines of code from **sbvirtualdisplay**, so perhaps your issue is an external dependency.

**Comment by mdmintz** [comment]
As indicated in multiple other issues you've opened (https://github.com/urllib3/urllib3/issues?q=is%3Aissue+author%3Akloczek+), use pip to install packages in a virtualenv, and use pytest to run any tests in that environment. What you're trying to do is neither typical, nor supported.
